name: build docker image on pull request

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker build
      uses: docker/setup-buildx-action@v2

    - name: Build and test docker image
      run:  |
            docker buildx create --use
            docker buildx build \
              --file Dockerfile \
              --tag  akhilsinghrana/personal-website:latest .

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1

  
