name: docker build and publish for akhilsinghrana.com on merge/push

concurrency:
  group: production
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:

    name: Push docker image to google artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: google-AR
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{vars.PROJECT_NAME}}
        workload_identity_provider: ${{vars.WID}}
    
    # Authenticate Docker to Google Cloud Artifact Registry
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ vars.SERVICE_LOCATION }}-docker.pkg.dev'
    
    - name: Build and Push Container
      run: |-
        docker build -t "${{ VARS.ARTIFACT_LOCATION }}:${{ github.sha }}" ./
        docker push "${{ VARS.ARTIFACT_LOCATION }}:${{ github.sha }}" 
      

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      env_var: ${{ vars.ENV_CONTEXT_VAR }}


  