name: docker build for akhilsinghrana.com

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker build
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME}} --password-stdin

    - name: Build and push docker image
      run:  |
            docker buildx create --use
            docker buildx build \
              --file Dockerfile \
              --tag  akhilsinghrana/personal-website:latest .
    
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1

  
